parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
pr:
  branches:
    include:
      - main
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - "*"

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/heads/main

extends:
  template: /pipelines/common-app-build.yaml@DEFRA-ADPPipelineCommon
  parameters:
    teamName: "ncea-search"
    serviceName: "ncea-elasticsearch"
    deployFromFeature: ${{ parameters.deployFromFeature }}
    includePlatformEnvs: true
    appBuildConfig:
      appFrameworkType: "helm"
      projectPath: "helm/ncea-elasticsearch/Chart.yaml"
      imageRepoName: "ncea-elasticsearch"

